SHOW_SQL: true
JWT_SECRET: EMPTY

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

remote-cqrs:
  http:
    remote-modules:
      - moduleName: users
        url: http://localhost:8081/api/cqrs