server:
  error:
    include-message: always
  port: 8081

management:
  server:
    port: 9081
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
  file:
    name: logs/context-auth-ms-app.log

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: caffeine
    cache-names: usersCache,contextCache
    caffeine:
      spec: maximumSize=50000,expireAfterWrite=1h,expireAfterAccess=15m