server:
  error:
    include-message: always
  port: 8081

management:
  server:
    port: 9081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
    pg: debug
    org:
      springframework:
        security: debug
        web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{app-trace-id}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/context-auth-ms-app.log

spring:
  application:
    name: context-auth-microservice

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: caffeine
    cache-names: usersCache,contextCache
    caffeine:
      spec: maximumSize=50000,expireAfterWrite=1h,expireAfterAccess=15m